"""The shared shape of a buy/sell signal, for every asset class (docs/dev/RESEARCH_ROADMAP.md, section D).

Ground rules, enforced by review and tests rather than types:
1. A signal is a probability of a defined event over a horizon, with a range. It is never a command.
2. Python computes the signal from public data and fincalc maths. An LLM may explain it but cannot change it.
3. Every signal names its method and how it was validated. Until the validation has enough resolved cases it says
   "uncalibrated", and the UI shows that.
4. It is personal research, not investment advice (SEBI: the owner is not a registered RA/IA). Don't distribute.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Literal

Asset = Literal["ipo", "stock", "fund", "bond", "fno"]
Action = Literal[
    "APPLY", "SKIP",  # IPO before allotment
    "SELL_AT_LISTING", "HOLD_AFTER_LISTING",  # IPO on listing day
    "BUY", "ACCUMULATE", "HOLD", "REDUCE", "SELL", "AVOID",  # stocks, funds, bonds
    "ENTER", "WAIT", "EXIT",  # F&O strategies
    "NO_SIGNAL",  # not enough data to say anything honest
]  # fmt: skip
ValidationStatus = Literal["backtested", "base_rate", "rule_based", "uncalibrated"]

DISCLAIMER = (
    "Personal research generated by FinResearch with public data and stated maths. Not investment advice; the owner is "
    "not a SEBI-registered research analyst or investment adviser. Do not distribute."
)


@dataclass
class Factor:
    """One input to the signal and how it pushed the score (`contribution` in the score's own units)."""

    name: str
    value: float | str | None
    contribution: float  # signed; the contributions of all factors add up to the score (before clipping)
    explanation: str  # plain English: what it is and why it matters, one or two sentences
    source: str | None = None  # URL, "fincalc:<function>", or "claim:<id>"
    unit: str | None = None


@dataclass
class Validation:
    """How the method was checked, with honest numbers. `n` is the number of resolved cases behind the metrics."""

    status: ValidationStatus
    n: int = 0
    metrics: dict[str, float] = field(
        default_factory=dict
    )  # e.g. {"brier": 0.19, "brier_skill": 0.07, "auc": 0.71}
    description: str = ""  # e.g. "walk-forward 2019-2026, positive Brier skill in 6 of 7 years"


@dataclass
class Signal:
    asset: Asset
    instrument: str  # NSE symbol, ISIN, AMFI scheme code or F&O strategy id
    name: str | None
    action: Action
    score: float  # -100 (strong negative) .. +100 (strong positive); 0 is neutral
    event: str  # the event the probability is about, e.g. "listing-day open above the issue price"
    horizon: str  # e.g. "listing day", "12 months", "until expiry"
    method: str  # e.g. "empirical base rate by QIB band (post-2022)", "rule-based composite v1"
    validation: Validation
    probability: float | None = None  # P(event), 0..1
    probability_interval: tuple[float, float] | None = None  # e.g. a 95 % Wilson interval
    expected_return: dict[str, float] | None = (
        None  # quantiles, e.g. {"p10": -0.05, "p50": 0.12, "p90": 0.40}
    )
    base_rate: dict[str, Any] | None = None  # {"n": 83, "p": 0.78, "ci": [0.68, 0.86], "description": "..."}
    factors: list[Factor] = field(default_factory=list)
    caveats: list[str] = field(default_factory=list)
    sizing: dict[str, Any] | None = (
        None  # e.g. {"max_lots": 1, "reason": "..."}; never above the profile's limits
    )
    sources: list[str] = field(default_factory=list)
    as_of: datetime | None = None
    disclaimer: str = DISCLAIMER

    def to_json(self) -> dict[str, Any]:
        out = asdict(self)
        out["as_of"] = self.as_of.isoformat() if self.as_of else None
        if self.probability_interval is not None:
            out["probability_interval"] = list(self.probability_interval)
        return out


def action_for_score(score: float, *, positive: str = "BUY", mild: str = "ACCUMULATE", neutral: str = "HOLD",
                     negative: str = "REDUCE", strong_negative: str = "SELL") -> str:  # fmt: skip
    """Map a score to an action with fixed, documented cut-offs (+50 / +20 / -20 / -50)."""
    if score >= 50:
        return positive
    if score >= 20:
        return mild
    if score > -20:
        return neutral
    if score > -50:
        return negative
    return strong_negative


def clip_score(x: float) -> float:
    return max(-100.0, min(100.0, x))
