"""monitoring watches jobs and alerts

Revision ID: 1a2c5e1768ff
Revises: 8869e1a3a7e4
Create Date: 2026-09-28 23:39:01.803161

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector type in autogenerated migrations)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1a2c5e1768ff"
down_revision: str | Sequence[str] | None = "8869e1a3a7e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("nse_symbol", sa.String(length=30), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("allotment_date", sa.Date(), nullable=False),
        sa.Column("listing_date", sa.Date(), nullable=False),
        sa.Column("anchor_shares", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watch_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["watch_id"], ["watch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_watch_id"), "alert", ["watch_id"], unique=False)
    op.create_table(
        "monitor_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watch_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("slot", sa.String(length=120), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["watch_id"], ["watch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot"),
    )
    op.create_index(op.f("ix_monitor_job_due_at"), "monitor_job", ["due_at"], unique=False)
    op.create_index(op.f("ix_monitor_job_status"), "monitor_job", ["status"], unique=False)
    op.create_index(op.f("ix_monitor_job_watch_id"), "monitor_job", ["watch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitor_job_watch_id"), table_name="monitor_job")
    op.drop_index(op.f("ix_monitor_job_status"), table_name="monitor_job")
    op.drop_index(op.f("ix_monitor_job_due_at"), table_name="monitor_job")
    op.drop_table("monitor_job")
    op.drop_index(op.f("ix_alert_watch_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_table("watch")
    # ### end Alembic commands ###
