"""claim gate checks and corrections

Revision ID: 1b9c18dea179
Revises: a62a6887588b
Create Date: 2026-09-28 19:46:00.444230

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector type in autogenerated migrations)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b9c18dea179"
down_revision: str | Sequence[str] | None = "a62a6887588b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "claim",
        sa.Column(
            "checks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column("claim", sa.Column("corrects_claim_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "claim", "claim", ["corrects_claim_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "claim", type_="foreignkey")
    op.drop_column("claim", "corrects_claim_id")
    op.drop_column("claim", "checks")
    # ### end Alembic commands ###
