"""investor profile and decision journal

Revision ID: 8869e1a3a7e4
Revises: eb7fb18f1fe1
Create Date: 2026-09-28 23:10:58.935809

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector type in autogenerated migrations)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8869e1a3a7e4"
down_revision: str | Sequence[str] | None = "eb7fb18f1fe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investor_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("lots", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column(
            "suggestion",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("user_action", sa.String(length=20), nullable=True),
        sa.Column("applied_lots", sa.Integer(), nullable=True),
        sa.Column("allotted_lots", sa.Integer(), nullable=True),
        sa.Column("issue_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("listing_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column(
            "outcome",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["research_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decision_company_id"), "decision", ["company_id"], unique=False)
    op.create_index(op.f("ix_decision_run_id"), "decision", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decision_run_id"), table_name="decision")
    op.drop_index(op.f("ix_decision_company_id"), table_name="decision")
    op.drop_table("decision")
    op.drop_table("investor_profile")
    # ### end Alembic commands ###
