"""stock watches

Revision ID: 9a4a02fd012e
Revises: 1a2c5e1768ff
Create Date: 2026-09-29 01:00:19.333492

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector type in autogenerated migrations)
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a4a02fd012e"
down_revision: str | Sequence[str] | None = "1a2c5e1768ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("watch", sa.Column("kind", sa.String(length=20), server_default="ipo", nullable=False))
    op.alter_column("watch", "open_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("watch", "close_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("watch", "allotment_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("watch", "listing_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("watch", "listing_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("watch", "allotment_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("watch", "close_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("watch", "open_date", existing_type=sa.DATE(), nullable=False)
    op.drop_column("watch", "kind")
    # ### end Alembic commands ###
