"""agent steps and run resume time

Revision ID: a62a6887588b
Revises: e7dec79fdbb5
Create Date: 2026-09-28 18:07:06.010045

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector type in autogenerated migrations)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a62a6887588b"
down_revision: str | Sequence[str] | None = "e7dec79fdbb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=True),
        sa.Column("model", sa.String(length=60), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cost_usd_est", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("num_turns", sa.Integer(), nullable=True),
        sa.Column("five_hour_before", sa.Float(), nullable=True),
        sa.Column("five_hour_after", sa.Float(), nullable=True),
        sa.Column("transcript_path", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["research_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "key"),
    )
    op.create_index(op.f("ix_agent_step_run_id"), "agent_step", ["run_id"], unique=False)
    op.create_index(op.f("ix_agent_step_status"), "agent_step", ["status"], unique=False)
    op.add_column("research_run", sa.Column("resume_after", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_run", "resume_after")
    op.drop_index(op.f("ix_agent_step_status"), table_name="agent_step")
    op.drop_index(op.f("ix_agent_step_run_id"), table_name="agent_step")
    op.drop_table("agent_step")
    # ### end Alembic commands ###
