"""initial schema: documents, sections, chunks, claim ledger, ipo data

Revision ID: e7dec79fdbb5
Revises:
Create Date: 2026-09-28 16:41:05.010725

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7dec79fdbb5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("cin", sa.String(length=30), nullable=True),
        sa.Column("nse_symbol", sa.String(length=30), nullable=True),
        sa.Column("bse_code", sa.String(length=20), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_company_nse_symbol"), "company", ["nse_symbol"], unique=False)
    op.create_table(
        "subscription_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nse_symbol", sa.String(length=30), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("total_times", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nse_symbol", "as_of", "source"),
    )
    op.create_index(
        op.f("ix_subscription_snapshot_nse_symbol"), "subscription_snapshot", ["nse_symbol"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("text_path", sa.Text(), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.Column("scanned_pages", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_index(op.f("ix_document_company_id"), "document", ["company_id"], unique=False)
    op.create_table(
        "ipo_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("nse_symbol", sa.String(length=30), nullable=True),
        sa.Column("open_date", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("price_low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("fresh_issue_cr", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ofs_cr", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ipo_offer_company_id"), "ipo_offer", ["company_id"], unique=False)
    op.create_index(op.f("ix_ipo_offer_nse_symbol"), "ipo_offer", ["nse_symbol"], unique=False)
    op.create_table(
        "research_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_run_company_id"), "research_run", ["company_id"], unique=False)
    op.create_table(
        "claim",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("stream", sa.String(length=60), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=20), nullable=False),
        sa.Column("metric", sa.String(length=120), nullable=True),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("period", sa.String(length=60), nullable=True),
        sa.Column("importance", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verifier_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claim_run_id"), "claim", ["run_id"], unique=False)
    op.create_index(op.f("ix_claim_status"), "claim", ["status"], unique=False)
    op.create_table(
        "document_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("text_source", sa.String(length=20), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_no"),
    )
    op.create_index(op.f("ix_document_page_document_id"), "document_page", ["document_id"], unique=False)
    op.create_table(
        "section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("canonical", sa.String(length=60), nullable=False),
        sa.Column("heading", sa.String(length=300), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_section_document_id"), "section", ["document_id"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embed_model", sa.String(length=80), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_document_id"), "chunk", ["document_id"], unique=False)
    op.create_index(
        "ix_chunk_embedding_hnsw",
        "chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_chunk_tsv", "chunk", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "citation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("quote_found", sa.Boolean(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["claim_id"], ["claim.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_citation_claim_id"), "citation", ["claim_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_citation_claim_id"), table_name="citation")
    op.drop_table("citation")
    op.drop_index("ix_chunk_tsv", table_name="chunk", postgresql_using="gin")
    op.drop_index(
        "ix_chunk_embedding_hnsw",
        table_name="chunk",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_chunk_document_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_section_document_id"), table_name="section")
    op.drop_table("section")
    op.drop_index(op.f("ix_document_page_document_id"), table_name="document_page")
    op.drop_table("document_page")
    op.drop_index(op.f("ix_claim_status"), table_name="claim")
    op.drop_index(op.f("ix_claim_run_id"), table_name="claim")
    op.drop_table("claim")
    op.drop_index(op.f("ix_research_run_company_id"), table_name="research_run")
    op.drop_table("research_run")
    op.drop_index(op.f("ix_ipo_offer_nse_symbol"), table_name="ipo_offer")
    op.drop_index(op.f("ix_ipo_offer_company_id"), table_name="ipo_offer")
    op.drop_table("ipo_offer")
    op.drop_index(op.f("ix_document_company_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_subscription_snapshot_nse_symbol"), table_name="subscription_snapshot")
    op.drop_table("subscription_snapshot")
    op.drop_index(op.f("ix_company_nse_symbol"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
